name: CI-setup

on: [push, pull_request]

jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Create dotfiles directory
      run: mkdir ~/dotfiles
    
    - name: Copy dotfiles into HOME
      run: cp -r . ~/dotfiles

    - name: Stow
      run: |
        sudo apt install -y stow
        cd ~/dotfiles
        stow . --adopt
    
    - name: Run setup
      run: |
        source ~/dotfiles/.profile
        echo "================================================================"
        env
        echo "================================================================"
        source ~/dotfiles/setup/setup.sh

    - name: Run tests
      run: ./tests/runtests.sh